import type { Metadata } from "next"; // Importing type for metadata used in the layout
import { Geist, Geist_Mono } from "next/font/google"; // Importing custom Google fonts
import "./globals.css"; // Global styles applied throughout the app

// Configure Geist Sans font with a custom CSS variable and Latin subset
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Configure Geist Mono font with a custom CSS variable and Latin subset
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define the default metadata for the application
export const metadata: Metadata = {
  title: "Create Next App", // Title shown in the browser tab
  description: "Generated by create next app", // Short description for SEO
};

// Root layout component that wraps all pages of the app
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // Accepts any child components (pages, components, etc.)
}>) {
  return (
    <html lang="en">
      {/* Apply the imported fonts and enable font smoothing */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children} {/* Render the child components inside the layout */}
      </body>
    </html>
  );
}
